// src/utils/mappingUtil.js
import stringSimilarity from 'string-similarity';


// Mapping dictionary: UI keys (normalized) -> canonical backend keys.
const CANONICAL_FIELDS  = {
    "title": "title",
    "prefix": "title",
    "first name": "first_name",
    "given name": "first_name",
    "firstname": "first_name",
    "first": "first_name",
    "first_name": "first_name",
    "surname": "last_name",
    "lastname": "last_name",
    "last name": "last_name",
    "last": "last_name",
    "last_name": "last_name",
    "middle name(s)": "middle_name",  
    "middle name": "middle_name",
    "middle": "middle_name",
    "middle initial": "middle_name",
    "middle_name": "middle_name",
    "family name": "last_name",
    "family": "last_name",
    "family_name": "last_name",

    "sex": "gender",
    "gender": "gender",

    "dob": "date_of_birth",
    "date of birth": "date_of_birth",
    "birth date": "date_of_birth",
    "birthdate": "date_of_birth",
    "date_of_birth": "date_of_birth",
    "birthday": "date_of_birth",
    "email": "email",
    "e-mail": "email",
    "email address": "email",
    "email input": "email",
    "email_input": "email",
    "mail": "email",
    "electronic mail": "email",
    "electronicmail": "email",
    "electronic-mail": "email",
    "electronic_mail": "email",

    "mail address": "email",
    "phone number": "contact_info",
    "phone": "contact_info",
    "contact number": "contact_info",
    "contact": "contact_info",
    "employee type": "employee_type",
    "employee_type": "employee_type", // Synonym for employee_type
    "employment type": "employee_type",
    "employment_type": "employee_type",
    "employmenttype": "employee_type",
    "employment": "employee_type",
    "employee status": "employee_type",
    "employee_status": "employee_type",
    "employee status type": "employee_type",
    "employee_status_type": "employee_type",
    "appointment type": "employee_type",
    "appointment_type": "employee_type",
    "appointmenttype": "employee_type",
    "appointment": "employee_type",
    "employment status": "employee_type",
    "employment_status": "employee_type",
    "employment status type": "employee_type",
    "employment_status_type": "employee_type",
    "role selection": "role_id",
    "role selection input": "role_id",
    "user role": "role_id",
    "user role selection": "role_id",
    "user role input": "role_id",
    "user role select": "role_id",
    "user role select input": "role_id",
    "user role_id": "role_id",
    "role": "role_id",
    "role_select": "role_id",
    "system_role": "role_id",
    "role_select_input": "role_id",
    "system role": "role_id",
    "department": "assigned_dept",

    "residential address": "address",
    "residentialaddress": "address",
    "residential": "address",
    "residential_address": "address",
    "address": "address",
    "postal address": "address",
    "postaladdress": "address",
    "postal": "address",
    "postal_code": "address",  
    "postalcode": "address",
    "home": "address",  
    "home_address": "address",
    "home address": "address",
    "homeaddress": "address",
    "personal address": "address",
    "personaladdress": "address",
    "personal": "address",
    "personal_address": "address",
    "rank": "rank",
    "rank selection": "rank",
    "rank selection input": "rank",
    "rank input": "rank",
    "rank input field": "rank",
    "rank_select": "rank",
    "rank_select_input": "rank",
    "rank selection field": "rank",
    "rank selection field input": "rank",
    "assigned rank": "rank",
    "assignedrank": "rank",
    "assigned_rank": "rank",
    "assigned department": "assigned_dept",  
    "assigneddepartment": "assigned_dept", 
    "assigned dept": "assigned_dept",  
    "assigneddept": "assigned_dept",
    "academic qualifications": "academic_qualifications",
    "professional qualifications": "professional_qualifications",
    "payment details": "payment_details",
    "next of kin": "next_of_kin",
    "profile picture": "profile_image_path",
    "profile image": "profile_image_path",
    "profile image path": "profile_image_path",
    "profile picture path": "profile_image_path",
    "profile_image": "profile_image_path",
    "profile_image_path": "profile_image_path",
    "profile picture input": "profile_image_path",
    "profile picture input field": "profile_image_path",
    "profile picture upload": "profile_image_path",
    "profile picture upload field": "profile_image_path",
    "profile picture upload input": "profile_image_path",
    "profile picture upload input field": "profile_image_path",
    "profile picture upload input field": "profile_image_path",
    "profile picture upload input field": "profile_image_path",
    "profile picture upload input field": "profile_image_path",
    "passport image": "profile_image_path",
    "passport photo": "profile_image_path",
    "passport": "profile_image_path",
    "passport_image": "profile_image_path",
    "passport_photo": "profile_image_path",
    "passport_image_path": "profile_image_path",
    "passport_photo_path": "profile_image_path",
    "Ghana card": "custom_data",
    "ghana_card": "custom_data",
    "ghana_card_number": "custom_data",
    "ghana_card_number": "custom_data",
    "ghana_card_number": "custom_data",
    "ghana card front image": "custom_data",
    "ghana card front": "custom_data",
    "ghana_card_front": "custom_data",
    "ghana_card_front_image": "custom_data",
    "ghana card front image path": "custom_data",
    "ghana_card_front_image_path": "custom_data",
    "ghana card back image": "custom_data",
    "ghana card back": "custom_data",
    "ghana_card_back": "custom_data",
    "ghana_card_back_image": "custom_data",
    "ghana card back image path": "custom_data",
    "ghana_card_back_image_path": "custom_data",
    "ghana card front image path": "custom_data",
    "ghana_card_front_image_path": "custom_data",
    "ghana card back image path": "custom_data",
    "ghana card image": "custom_data",
    "ghana_card_image": "custom_data",
    "ghana card image path": "custom_data",
    "ghana_card_image_path": "custom_data",
    "ghana card number": "custom_data",
    "ghana_card_number": "custom_data",
    "ghana card number": "custom_data",
    "national id": "custom_data",
    "national_id": "custom_data",
    "national id number": "custom_data",
    "national_id_number": "custom_data",
    "national id image": "custom_data",
    "national_id_image": "custom_data",
    "national id image path": "custom_data",
    "national_id_image_path": "custom_data",
    "national id front image": "custom_data",
    "national_id_front_image": "custom_data",
    "national id front": "custom_data",
    // "submit button": "submit", // Normally empty
    // ... add as many synonyms as required.
  };

export const mapEmployeeFields = (inputData) => {
  const mapped = {};
  Object.entries(inputData).forEach(([key, value]) => {
    // Normalize the key for comparison.
    const normalizedKey = key.trim().toLowerCase();
    const candidateKeys = Object.keys(CANONICAL_FIELDS);
    const { bestMatch } = stringSimilarity.findBestMatch(normalizedKey, candidateKeys);
    // If the best match is good enough, use the canonical field name.
    if (bestMatch.rating > 0.6) {
      mapped[CANONICAL_FIELDS[bestMatch.target]] = value;
    } else {
      // Otherwise, keep the key as provided.
      mapped[key] = value;
    }
  });
  return mapped;
};

